/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package project1

class App {
    String getGreeting() {
	
        return 'Hello world!'
    }

    static void main(String[] args) {
        println new App().greeting
	
   	
    }
}
